export const PRODUCT_List_REQUEST='PRODUCT_List_REQUEST'
export const PRODUCT_LIST_SUCCESS='PRODUCT_List_SUCCESS'
export const PRODUCT_LIST_FAIL='PRODUCT_List_FAIL'

export const PRODUCT_DETAILS_REQUEST='PRODUCT_List_REQUEST'
export const PRODUCT_DETAILS_SUCCESS='PRODUCT_List_SUCCESS'
export const PRODUCT_DETAILS_FAIL='PRODUCT_List_FAIL'